# Project information
site_name: CMS Open Data Guide
site_description: 'CMS Open Data Guide'
site_url: 'https://cms-opendata-guide.web.cern.ch/'

# Repository
repo_name: 'cms-opendata-guide'
repo_url: 'https://github.com/cernopendata/cms-opendata-guide'

# Structure
nav:
    - Home: index.md
    - 'CMS Open Data':
        - 'CERN Open Data Portal': cmsOpenData/cernportal.md
        - 'CMS Open Data': cmsOpenData/cmsopendata.md
        - 'Finding Data': cmsOpenData/findingData.md
        - 'Workshops': cmsOpenData/workshops.md
    - 'Computing Tools':
        - 'UNIX': tools/unix.md
        - 'ROOT': tools/root.md
        - 'C++ and Python': tools/cppandpython.md
        - 'Git': tools/git.md
        - 'Docker': tools/docker.md
        - 'Virtual Machines': tools/virtualmachines.md
    - 'CMSSW':
        - 'Overview': cmssw/cmsswoverview.md
        - 'Data Model': cmssw/cmsswdatamodel.md
        - 'Analyzers': cmssw/cmsswanalyzers.md
        - 'Configuration': cmssw/cmsswconfigure.md
        - 'Conditions Data': cmssw/cmsswconditions.md
    - 'Analysis':
        - 'Data and Simulation':
            - 'Collision Data': analysis/datasim/collisiondata.md
            - 'MC Simulations': analysis/datasim/mcsimulations.md
            - 'Event Generation': analysis/datasim/eventgeneration.md
        - 'Selection':
            - 'Validated Runs': analysis/selection/validatedRuns.md
            - 'Triggers': analysis/selection/triggers.md
            - 'Physics Objects':
                - 'Physics Objects': analysis/selection/objects/objects.md
                - 'Common Tools': analysis/selection/objects/tools.md
                - 'Muons': analysis/selection/objects/muons.md
                - 'Electrons': analysis/selection/objects/electrons.md
                - 'Photons': analysis/selection/objects/photons.md
                - 'Jets': analysis/selection/objects/jets.md
                - 'Missing ET': analysis/selection/objects/met.md
                - 'Taus': analysis/selection/objects/taus.md
	    - 'Efficiency measurements': analysis/selection/idefficiencystudy/tagandprobe.md
        - 'Luminosity': analysis/lumi.md
        - 'Background Modelling': analysis/backgrounds.md
        - 'Corrections and Uncertainties':
            - 'Luminosity uncertainties': analysis/systematics/lumiuncertain.md
            - 'Pileup uncertainty': analysis/systematics/pileupuncertain.md
            - 'Generator uncertainty': analysis/systematics/mcuncertain.md
            - 'Physics Object Corrections':
                 - 'Lepton/Photon corrections': analysis/systematics/objectsuncertain/leptonuncertain.md
                 - 'Jet/MET corrections': analysis/systematics/objectsuncertain/jetmetuncertain.md
                 - 'Jet tagging corrections': analysis/systematics/objectsuncertain/btaguncertain.md
        - 'Statistical Interpretation': analysis/stats.md  
    - FAQ: faq.md
    - About: about.md

# Configuration
theme:
    name: material
    palette:
      scheme: 'default'
      primary: 'indigo'
      accent:
    font:
      text: 'Lato'
    icon:
      repo: 'fontawesome/brands/github'
    logo: 'images/cms-od.png'
    favicon: 'images/cms-od.png'

# Customization
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
# Extensions
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.arithmatex:
        generic: true
      
# Plugins
plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
